version: "3"

# 
services:
    db:
        image: postgres
        container_name: postgres
        environment: 
            - POSTGRES_USER=sa
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=api
        ports: 
            - 5432:5432
    redis:
        image: redis
        restart: always
        container_name: redis
        ports: 
            - 6379:6379
    